// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC1eDKM483ltqR2nFBqWy6IVr0pzhEQz8',
    appId: '1:82406700480:web:5d13c70df90a3936260425',
    messagingSenderId: '82406700480',
    projectId: 'tiktok-clone-567b9',
    authDomain: 'tiktok-clone-567b9.firebaseapp.com',
    storageBucket: 'tiktok-clone-567b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeDCg4MhsD0n6Pq5dpUVL-A1ZAe3_gZyQ',
    appId: '1:82406700480:android:9393830679e2ebca260425',
    messagingSenderId: '82406700480',
    projectId: 'tiktok-clone-567b9',
    storageBucket: 'tiktok-clone-567b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt7Wke0UqMtp-0dlA0H_5aEBxmfcYDztg',
    appId: '1:82406700480:ios:0bae9c34544beb6b260425',
    messagingSenderId: '82406700480',
    projectId: 'tiktok-clone-567b9',
    storageBucket: 'tiktok-clone-567b9.appspot.com',
    androidClientId: '82406700480-oboji6b05mdqoocquaqcnkgpsvaohmme.apps.googleusercontent.com',
    iosClientId: '82406700480-7p4o2s42tho0l54npql8bb3urksrkac6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt7Wke0UqMtp-0dlA0H_5aEBxmfcYDztg',
    appId: '1:82406700480:ios:aad80e5da6d0cc9c260425',
    messagingSenderId: '82406700480',
    projectId: 'tiktok-clone-567b9',
    storageBucket: 'tiktok-clone-567b9.appspot.com',
    androidClientId: '82406700480-oboji6b05mdqoocquaqcnkgpsvaohmme.apps.googleusercontent.com',
    iosClientId: '82406700480-hm733dchmdhnu0tp2mjl3rbn054fgcsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokclone.RunnerTests',
  );
}
